import { CartInterface } from "@/components/types/cartType";

export const poplulars: CartInterface[] = [
    {
        id: 1,
        title: "Bruce Springsteen",
        date: "12.05.2024",
        time: "16:30",
        price: "33.5",
        location: "Frankfurt",
        category: "music",
        img: "music",
    },
    {
        id: 2,
        title: "AFROCROWD ZOOM HALLOWEEN NIGHT",
        date: "12.05.2024",
        time: "16:30",
        price: "22.49",
        location: "ZOOM Frankfurt",
        category: "hobby",
        img: "hobby",
    },
    {
        id: 3,
        title: "Stand-up Comedy cu Natanticu, Andrei Ciobanu și Raul Gheba",
        date: "12.05.2024",
        time: "16:30",
        price: "21.30",
        location: "Jahrhunderthalle Club",
        category: "theater",
        img: "comedy",
    },
    {
        id: 4,
        title: "Eintracht Frankfurt ",
        date: "12.05.2024",
        time: "16:30",
        price: "33.5",
        location: "Frankfurt",
        category: "sport",
        img: "sport",
    },
    {
        id: 5,
        title: "FISA Garba & Bollywood Night",
        date: "12.05.2024",
        time: "16:30",
        price: "12.00",
        location: "Friedrich-Dessauer-Haus",
        category: "theater",
        img: "theater",
    },
];
